(ns drill.generator
  (:require [babashka.process :as proc]
            [clojure.java.io  :as io]
            [clojure.string   :as str]
            [drill.drift      :as drift]
            [drill.prompt     :as prompt]
            [drill.registry   :as reg]))

(def ^:dynamic *generated-dir* "drill_generated")

(def ^:dynamic *llm-call*
  (fn [text]
    (let [{:keys [out exit err]}
          (proc/shell {:in text :out :string :err :string :continue true}
                      "claude" "-p")]
      (if (zero? exit)
        out
        (throw (ex-info "claude CLI failed"
                        {:type :drill/llm-call-failed :exit exit :stderr err}))))))

(defn- extract-block [response]
  (if-let [match (re-find #"(?s)```clojure\s*\n(.*?)\n?```" response)]
    (second match)
    (throw (ex-info "generation-failed: no ```clojure``` block in response"
                    {:type :drill/generation-failed :response response}))))

(defn- header [hash]
  (str ";; AUTO-GENERATED by drill.\n"
       ";; spec-hash: " hash "\n"
       ";; Manual edits will be overwritten on regeneration.\n"))

(defn- id->filename [id]
  (-> id name (str/replace "-" "_")))

(defn- id->path [id]
  (str *generated-dir* "/" (id->filename id) ".clj"))

(defn gen-feature! [spec]
  (let [siblings    (->> (vals @reg/descriptions)
                         (remove #(= (:id %) (:id spec))))
        prompt-text (prompt/build spec siblings)
        response    (*llm-call* prompt-text)
        body        (extract-block response)
        h           (drift/spec-hash spec)
        content     (str (header h) body)
        path        (id->path (:id spec))]
    (io/make-parents path)
    (spit path content)
    {:id (:id spec) :status :generated :path path}))
