(ns drill.generator
  (:require [babashka.process :as proc]
            [clojure.java.io  :as io]
            [clojure.string   :as str]
            [drill.drift      :as drift]
            [drill.prompt     :as prompt]
            [drill.registry   :as reg]
            [drill.trace      :as trace]))

(def ^:dynamic *generated-dir* "drill_generated")

(def ^:dynamic *llm-call*
  (fn [text]
    (let [{:keys [out exit err]}
          (proc/shell {:in text :out :string :err :string :continue true}
                      "claude" "-p")]
      (if (zero? exit)
        out
        (throw (ex-info "claude CLI failed"
                        {:type :drill/llm-call-failed :exit exit :stderr err}))))))

(defn- extract-block [response]
  (if-let [match (re-find #"(?s)```clojure\s*\n(.*?)\n?```" response)]
    (second match)
    (throw (ex-info "generation-failed: no ```clojure``` block in response"
                    {:type :drill/generation-failed :response response}))))

(defn- header [hash]
  (str ";; AUTO-GENERATED by drill.\n"
       ";; spec-hash: " hash "\n"
       ";; Manual edits will be overwritten on regeneration.\n"))

(defn- id->filename [id]
  (-> id name (str/replace "-" "_")))

(defn- id->path [id]
  (str *generated-dir* "/" (id->filename id) ".clj"))

(defn- smoke! [spec path]
  (try
    (load-file path)
    (catch Exception e
      (throw (ex-info (str "generated-impl-broken: load failed for " (:id spec))
                      {:type :drill/generated-impl-broken :id (:id spec) :path path}
                      e))))
  (let [impl (reg/lookup (:id spec))]
    (when-not impl
      (throw (ex-info (str "generated-impl-broken: :id " (:id spec)
                           " not registered after load")
                      {:type :drill/generated-impl-broken :id (:id spec) :path path})))
    (doseq [[_tag case-spec] (:cases spec)
            {tag-and-args :in expected :out} (:examples case-spec)]
      (let [actual (impl tag-and-args)]
        (when (not= expected actual)
          (throw (ex-info (str "generated-impl-broken: example mismatch for "
                               (:id spec))
                          {:type :drill/generated-impl-broken
                           :id (:id spec)
                           :example-in tag-and-args
                           :expected expected
                           :actual actual})))))))

(defn gen-feature! [spec]
  (let [siblings    (->> (vals @reg/descriptions)
                         (remove #(= (:id %) (:id spec))))
        prompt-text (prompt/build spec siblings)]
    (trace/emit :info {:stage :prompt-built :id (:id spec) :prompt-length (count prompt-text)})
    (trace/emit :debug {:stage :prompt-built :id (:id spec) :prompt-length (count prompt-text) :prompt prompt-text})
    (trace/emit :info {:stage :llm-call-start :id (:id spec)})
    (let [start    (System/currentTimeMillis)
          response (*llm-call* prompt-text)
          elapsed  (- (System/currentTimeMillis) start)]
      (trace/emit :info {:stage :llm-call-done :id (:id spec) :elapsed-ms elapsed :response-length (count response)})
      (trace/emit :debug {:stage :llm-call-done :id (:id spec) :elapsed-ms elapsed :response-length (count response) :response response})
      (let [body    (extract-block response)
            _       (trace/emit :debug {:stage :block-extracted :id (:id spec) :block-length (count body)})
            h       (drift/spec-hash spec)
            content (str (header h) body)
            path    (id->path (:id spec))]
        (io/make-parents path)
        (spit path content)
        (trace/emit :info {:stage :file-written :id (:id spec) :path path :spec-hash h})
        (smoke! spec path)
        (let [example-count (->> (:cases spec) vals (mapcat :examples) count)]
          (trace/emit :info {:stage :smoke-pass :id (:id spec) :example-count example-count}))
        {:id (:id spec) :status :generated :path path}))))
