(ns drill.drift-test
  (:require [clojure.test :refer [deftest is testing]]
            [drill.drift :as drift]))

(def spec-a {:id :x :cases {:c {:input :string :output :string}}})
(def spec-a-reordered {:cases {:c {:output :string :input :string}} :id :x})

(deftest spec-hash-is-stable-under-key-order
  (is (= (drift/spec-hash spec-a) (drift/spec-hash spec-a-reordered))))

(deftest spec-hash-changes-when-content-changes
  (is (not= (drift/spec-hash spec-a)
            (drift/spec-hash (assoc-in spec-a [:cases :c :desc] "added")))))

(deftest header-hash-parses-the-marker
  (is (= "abc123" (drift/header-hash ";; AUTO-GENERATED by drill.\n;; spec-hash: abc123\n(ns ...)"))))

(deftest header-hash-nil-when-missing
  (is (nil? (drift/header-hash "(ns plain)"))))

(deftest status-missing-when-no-file
  (is (= :missing (drift/status spec-a nil))))

(deftest status-fresh-when-hash-matches
  (let [h (drift/spec-hash spec-a)
        file (str ";; spec-hash: " h "\n(ns x)")]
    (is (= :fresh (drift/status spec-a file)))))

(deftest status-stale-when-hash-differs
  (let [file ";; spec-hash: deadbeef\n(ns x)"]
    (is (= :stale (drift/status spec-a file)))))
