(ns drill.generator-test
  (:require [clojure.test :refer [deftest is testing use-fixtures]]
            [clojure.java.io :as io]
            [clojure.string :as str]
            [drill.registry  :as reg]
            [drill.generator :as gen]
            [drill.drift     :as drift]))

(def tmp-dir "test/tmp/drill_generated")

(use-fixtures :each
  (fn [t]
    (reg/clear!)
    (.mkdirs (io/file tmp-dir))
    (binding [gen/*generated-dir* tmp-dir]
      (t))
    (doseq [f (.listFiles (io/file tmp-dir))] (.delete f))))

(def spec {:id :greet :cases {:hi {:input [:tuple [:= :hi] :string] :output :string}}})

(def llm-response
  (str "```clojure\n"
       "(ns drill-generated.greet (:require [drill.registry :as r]))\n"
       "(defn -impl [[_tag name]] (str \"hi \" name))\n"
       "(r/register-impl! :greet -impl)\n"
       "```\n"))

(deftest extract-block-strips-fences
  (is (str/includes? (#'gen/extract-block llm-response) "(defn -impl")))

(deftest extract-block-throws-on-missing-fence
  (is (thrown-with-msg? clojure.lang.ExceptionInfo #"generation-failed"
        (#'gen/extract-block "plain text response"))))

(deftest gen-feature-writes-file-with-header
  (binding [gen/*llm-call* (constantly llm-response)]
    (let [result  (gen/gen-feature! spec)
          file    (slurp (:path result))]
      (is (= :generated (:status result)))
      (is (str/starts-with? file ";; AUTO-GENERATED by drill."))
      (is (str/includes? file (str ";; spec-hash: " (drift/spec-hash spec))))
      (is (str/includes? file "(defn -impl")))))

(deftest gen-feature-puts-file-at-id-based-path
  (binding [gen/*llm-call* (constantly llm-response)]
    (let [result (gen/gen-feature! spec)]
      (is (= (str tmp-dir "/greet.clj") (:path result))))))

(deftest gen-feature-translates-hyphens-in-id
  (binding [gen/*llm-call* (constantly llm-response)]
    (let [result (gen/gen-feature! (assoc spec :id :two-words))]
      (is (= (str tmp-dir "/two_words.clj") (:path result))))))
