;; AUTO-GENERATED by drill.
;; spec-hash: 47a8eb7d004e52a3
;; Manual edits will be overwritten on regeneration.
(ns drill-generated.compute
  (:require [drill.registry :as r] [sci.core :as sci]))
(defn -impl [[_tag expr]] (double (sci/eval-string expr)))
(r/register-impl! :compute -impl)