;; AUTO-GENERATED by drill.
;; spec-hash: 1d56dd1a839f3ea7
;; Manual edits will be overwritten on regeneration.
(ns drill-generated.ui (:require [drill.registry :as r]))
(defn -impl [[tag & args]]
  (case tag
    :get+wait-query     "what is two plus two"
    :confirm+wait-query true
    :set-result         true
    :in-progress        true))
(r/register-impl! :ui -impl)