;; AUTO-GENERATED by drill.
;; spec-hash: 1d56dd1a839f3ea7
;; Manual edits will be overwritten on regeneration.
(ns drill-generated.ui
  (:require [clojure.string :as str]
            [drill.registry :as r]))

(defn- read-yes-no []
  (loop []
    (let [input (some-> (read-line) str/trim str/lower-case)]
      (cond
        (nil? input)          false
        (#{"y" "yes"} input)  true
        (#{"n" "no"} input)   false
        :else (do (print "  Please enter y or n: ")
                  (flush)
                  (recur))))))

(defn -impl [[tag & args]]
  (case tag
    :get+wait-query
    (do (print "» ")
        (flush)
        (or (read-line) ""))

    :confirm+wait-query
    (let [[value] args]
      (println value)
      (print "  Confirm? [y/n] ")
      (flush)
      (read-yes-no))

    :set-result
    (let [[result] args]
      (println "Result: " result)
      true)

    :in-progress
    (let [[busy?] args]
      (if busy?
        (do (println "⏳ Working...") (flush))
        (do (println "\r\033[K") (flush)))
      true)))

(r/register-impl! :ui -impl)
